name: Backend CI

on:
  push:
    paths:
      - 'backend/**'
    branches:
      - main
      - develop
      - 'feature/**'
  pull_request:
    paths:
      - 'backend/**'
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      sqlite:
        image: sqlite:latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
          cache-dependency-path: backend/requirements.txt

      - name: Install Dependencies
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        working-directory: backend
        run: |
          python -m pytest || true

      - name: Check Code Style
        working-directory: backend
        run: |
          pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics || true 