name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - uses: actions/checkout@v3

      - name: Deploy to Production
        run: |
          echo "🚀 Despliegue a producción"
          # Aquí irían los pasos de despliegue específicos
          # Por ejemplo:
          # - Construir imágenes Docker
          # - Subir a un registro de contenedores
          # - Desplegar en el servidor de producción

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build Frontend
        working-directory: frontend
        run: |
          npm ci
          npm run build

      - name: Build Backend
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt 